### ISSUE TITLE
issue while deploying video-recorder-service.war

### ISSUE THREAD

**Issue by Sayanava** [Comcast/cats#12]
I am getting the following issue while deploying video-recorder-service.war

The console log while running standalone.sh script is uploaded at the following location:-
http://s000.tinyupload.com/?file_id=97602354453101097744
The server.log is uploaded in:-
http://s000.tinyupload.com/?file_id=01663517382331756773
The standalone-full.xml is uploaded at:-
http://s000.tinyupload.com/?file_id=75676604758362514384
And the JBoss CLI console log having the error message is uploaded at:-
http://s000.tinyupload.com/?file_id=52623340471585724359

MySQL has the database pvr_db with Empty set.
I installed the MySQL driver as a deployment since as a module it was not getting reflected.
Request your help on this.

**Comment by sajayjk** [comment]
Duplicate of https://github.com/Comcast/cats/issues/11

**Comment by Sayanava** [comment]
Yeah Sajay.But we get the same issue along with the updated logs and xml files which I have shared in this issue.
Request your help on this.

**Comment by sajayjk** [comment]
This could be due to multiple issues

1) You are configuring standalone-full.xml but Jboss is configured to use standalone.xml
2) MySQL username/password is wrong
3) Driver installed for JBoss is wrong ( or wrongly configured).

Please ensure that JBoss has connectivity with the datasource. This can be checked from the admin console for Jboss. This will ensure that JBoss has the correct MySQL driver installed and it is configured correctly. If Jboss can successfully connect, then we can take deeper look into it from CATS.

Go to JBoss Admin Console, Click on Profile, Click on Datasources (under Connector), select the datasource, click on Connection Tab and hit Test Connection

**Comment by sajayjk** [comment]
![Uploading Capture.PNG…]()

**Comment by Sayanava** [comment]
Thanks Sajay.There was some issues related to MySQL privileges.Able to deploy video-recorder-service.war successfully now.
