### ISSUE TITLE
Key Manager (Keys) tab does not display any info in the table below for a newly added Remote

### ISSUE THREAD

**Issue by ivanherrera402** [Comcast/cats#5]
In keymanager web ui what does the Key Tab do and what does the Layout tab do?

**Comment by sajayjk** [comment]
You may ignore the other tabs since they are provided to support GC100 which is another IR Blaster like IrnetboxPro. GC100 requires PRONTO codes for the keys. 

Since you have Irnetbox, the steps mentioned in the wiki should be enough.

The layout is used to define how the keys should be arranged when we display the remote in CATSVision. That is for which section,  row and column each key should be placed at and what its colors should be. If not provided the default layout will be used.

**Comment by ivanherrera402** [comment]
Sajay,

   Not sure what you mean by other tabs?

Here are the tabs

-          Home

-          Remotes

-          Formats

-          Keys

-          Layouts

-          Manage IrNetBox

-          Manage RedratHubs

Could you please specify what tabs above fall under other tab?

Thanks,

Ivan

**Comment by sajayjk** [comment]
For adding a new Remote (while dealing with Irnetbox) the only tab that is of interest is the Remotes Tab, which as per my understanding, you have already added a remote to.
